import { defineIntegration, createRestHandler } from '@weldable/integration-core'

const rest = createRestHandler()

export default defineIntegration({
  id: 'discord',
  version: 1,
  name: 'Discord',
  description: 'Send messages and manage channels in Discord servers.',
  icon: 'discord',
  exampleUsage: 'Send the release notes to our announcements channel',
  auth: {
    type: 'oauth2',
    test: async (_, ctx) => ctx.http.get('/users/@me').then(r => r.data as Record<string, unknown>),
  },
  baseUrl: 'https://discord.com/api/v10',
  headers: { 'Content-Type': 'application/json' },
  authHeaderPattern: 'Bot {token}',
  botTokenEnvVar: 'DISCORD_BOT_TOKEN',
  nangoProvider: 'discord',
  nangoScopes: 'bot',
  nangoCredentialEnvPrefix: 'DISCORD',
  nangoAuthorizationParams: { permissions: '274877983824' },

  actions: [
    // ── Messages ─────────────────────────────────────────────
    {
      actionId: 'send_message',
      name: 'Send message',
      description: 'Send or post a message to a Discord channel.',
      intents: [
        'post in discord',
        'message a discord channel',
        'say something in discord',
        'announce in discord',
        'drop a message in discord',
        'notify the discord server',
        'message the server',
        'send a message to the discord server',
        'chat in a channel',
        'tell the team in discord',
        'write to our discord',
        'share an update in discord',
      ],
      preview: '#{channel_id}: {content}',
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel to send the message to.',
        },
        {
          name: 'content',
          type: 'text',
          required: true,
          description: 'Message text (supports Discord markdown formatting).',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the sent message.' },
        { name: 'channel_id', type: 'string', description: 'ID of the channel the message was sent to.' },
        { name: 'timestamp', type: 'string', description: 'ISO 8601 timestamp when the message was sent.' },
        { name: 'content', type: 'string', description: 'Text content of the sent message.' },
      ],
      execute: rest({
        method: 'POST',
        path: '/channels/{channel_id}/messages',
        paramMapping: { channel_id: 'path', content: 'body' },
      }),
    },
    {
      actionId: 'read_messages',
      name: 'Read messages',
      description: 'Fetch recent messages from a Discord channel. Requires MESSAGE_CONTENT intent enabled in the Developer Portal to read message content.',
      intents: [
        'what was said in discord',
        'see recent messages',
        'check the discord channel',
        'read the latest discord messages',
        'pull messages from discord',
        "what's been posted in the channel",
        'show me the conversation in discord',
        'catch up on discord',
        'grab the last few messages from discord',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel to read messages from.',
        },
        {
          name: 'limit',
          type: 'number',
          required: false,
          description: 'Maximum number of messages to return (1-100).',
          default: 50,
        },
        {
          name: 'before',
          type: 'string',
          required: false,
          description: 'Get messages before this message ID.',
        },
        {
          name: 'after',
          type: 'string',
          required: false,
          description: 'Get messages after this message ID.',
        },
      ],
      outputFields: [
        { name: 'messages', type: 'array', description: 'Array of message objects, each with id, author (id, username), content, timestamp, and attachments.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/channels/{channel_id}/messages',
        paramMapping: { channel_id: 'path', limit: 'query', before: 'query', after: 'query' },
      }),
    },
    {
      actionId: 'get_message',
      name: 'Get message',
      description: 'Get a single message by ID from a Discord channel.',
      intents: [
        'get a specific discord message',
        'look up a message by ID',
        'fetch a single discord post',
        'retrieve a particular discord message',
        'show me a discord message by its ID',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel containing the message.',
        },
        {
          name: 'message_id',
          type: 'string',
          required: true,
          description: 'The ID of the message to retrieve.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the message.' },
        { name: 'channel_id', type: 'string', description: 'ID of the channel containing the message.' },
        { name: 'author', type: 'object', description: 'Author object with id and username.' },
        { name: 'content', type: 'string', description: 'Text content of the message.' },
        { name: 'timestamp', type: 'string', description: 'ISO 8601 timestamp when the message was sent.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/channels/{channel_id}/messages/{message_id}',
        paramMapping: { channel_id: 'path', message_id: 'path' },
      }),
    },
    {
      actionId: 'edit_message',
      name: 'Edit message',
      description: 'Edit a message in a Discord channel.',
      intents: [
        'update a discord message',
        'change a sent message',
        'fix a message in discord',
        'correct a discord message',
        'revise something already sent in discord',
        'modify a discord message',
        'reword a discord message',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel containing the message.',
        },
        {
          name: 'message_id',
          type: 'string',
          required: true,
          description: 'The ID of the message to edit.',
        },
        {
          name: 'content',
          type: 'text',
          required: false,
          description: 'New message text.',
        },
        {
          name: 'embeds',
          type: 'object',
          required: false,
          description: 'Array of embed objects.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the edited message.' },
        { name: 'channel_id', type: 'string', description: 'ID of the channel containing the message.' },
        { name: 'content', type: 'string', description: 'Updated text content of the message.' },
        { name: 'edited_timestamp', type: 'string', description: 'ISO 8601 timestamp when the message was last edited.' },
      ],
      execute: rest({
        method: 'PATCH',
        path: '/channels/{channel_id}/messages/{message_id}',
        paramMapping: { channel_id: 'path', message_id: 'path', content: 'body', embeds: 'body' },
      }),
    },
    {
      actionId: 'delete_message',
      name: 'Delete message',
      description: 'Delete a message from a Discord channel.',
      intents: [
        'remove a discord message',
        'take down a post in discord',
        'delete something from discord',
        'erase a message in discord',
        'get rid of a discord post',
        'wipe a message from the channel',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel containing the message.',
        },
        {
          name: 'message_id',
          type: 'string',
          required: true,
          description: 'The ID of the message to delete.',
        },
      ],
      outputFields: [
        { name: 'ok', type: 'boolean', description: 'True if the message was deleted successfully (Discord returns 204 No Content).' },
      ],
      execute: rest({
        method: 'DELETE',
        path: '/channels/{channel_id}/messages/{message_id}',
        paramMapping: { channel_id: 'path', message_id: 'path' },
      }),
    },
    {
      actionId: 'pin_message',
      name: 'Pin message',
      description: 'Pin a message in a channel.',
      intents: [
        'pin this in discord',
        'save a message to the pins',
        'highlight a message in the channel',
        'bookmark a discord message',
        'keep a message at the top of the channel',
        'mark a discord post as important',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel.',
        },
        {
          name: 'message_id',
          type: 'string',
          required: true,
          description: 'The ID of the message to pin.',
        },
      ],
      outputFields: [
        { name: 'ok', type: 'boolean', description: 'True if the message was pinned successfully (Discord returns 204 No Content).' },
      ],
      execute: rest({
        method: 'PUT',
        path: '/channels/{channel_id}/pins/{message_id}',
        paramMapping: { channel_id: 'path', message_id: 'path' },
      }),
    },
    {
      actionId: 'unpin_message',
      name: 'Unpin message',
      description: 'Unpin a message from a channel.',
      intents: [
        'unpin a message in discord',
        'remove from discord pins',
        'clear a pinned message',
        'take a message off the pinned list',
        'stop highlighting a discord message',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel.',
        },
        {
          name: 'message_id',
          type: 'string',
          required: true,
          description: 'The ID of the message to unpin.',
        },
      ],
      outputFields: [
        { name: 'ok', type: 'boolean', description: 'True if the message was unpinned successfully (Discord returns 204 No Content).' },
      ],
      execute: rest({
        method: 'DELETE',
        path: '/channels/{channel_id}/pins/{message_id}',
        paramMapping: { channel_id: 'path', message_id: 'path' },
      }),
    },
    {
      actionId: 'get_pinned_messages',
      name: 'Get pinned messages',
      description: 'Get all pinned messages in a channel.',
      intents: [
        "what's pinned in discord",
        'see pinned messages',
        'show channel pins',
        'list the pinned posts in a discord channel',
        'what has been pinned here',
        'view saved messages in discord',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel.',
        },
      ],
      outputFields: [
        { name: 'pinned_messages', type: 'array', description: 'Array of pinned message objects, each with id, author (id, username), content, and timestamp.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/channels/{channel_id}/pins',
        paramMapping: { channel_id: 'path' },
      }),
    },
    {
      actionId: 'search_messages',
      name: 'Search messages',
      description: 'Search messages in a Discord server by content, author, channel, or attachment type.',
      intents: [
        'find a message in discord',
        'search discord for',
        'look up old messages in discord',
        'find what someone said in discord',
        'dig up a conversation in discord',
        'hunt for a post in the server',
        'locate a message in discord',
        'scroll back and find something in discord',
      ],
      inputFields: [
        {
          name: 'guild_id',
          type: 'string',
          required: true,
          description: 'The ID of the server to search in.',
        },
        {
          name: 'content',
          type: 'string',
          required: false,
          description: 'Search for messages containing this text.',
        },
        {
          name: 'author_id',
          type: 'string',
          required: false,
          description: 'Filter by message author ID.',
        },
        {
          name: 'channel_id',
          type: 'string',
          required: false,
          description: 'Filter by channel ID.',
        },
        {
          name: 'has',
          type: 'string',
          required: false,
          description: 'Filter by attachment type: "link", "embed", "file", "video", "image", or "sound".',
        },
        {
          name: 'limit',
          type: 'number',
          required: false,
          description: 'Maximum number of results (1-25).',
          default: 25,
        },
      ],
      outputFields: [
        { name: 'messages', type: 'array', description: 'Array of arrays of message objects matching the search query, each with id, content, author, channel_id, and timestamp.' },
        { name: 'total_results', type: 'number', description: 'Total number of messages matching the search query.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/guilds/{guild_id}/messages/search',
        paramMapping: { guild_id: 'path', content: 'query', author_id: 'query', channel_id: 'query', has: 'query', limit: 'query' },
      }),
    },
    // ── Channels ─────────────────────────────────────────────
    {
      actionId: 'list_channels',
      name: 'List channels',
      description: 'List all channels in a Discord server.',
      intents: [
        'what channels are in this server',
        'show discord channels',
        'list all channels',
        'what channels exist in the server',
        'see all the rooms in the discord server',
        'browse the discord channel list',
        'what are the channels in this guild',
      ],
      inputFields: [
        {
          name: 'guild_id',
          type: 'string',
          required: true,
          description: 'The ID of the server.',
        },
      ],
      outputFields: [
        { name: 'channels', type: 'array', description: 'Array of channel objects, each with id, name, type (0=text, 2=voice, 4=category), position, and parent_id.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/guilds/{guild_id}/channels',
        paramMapping: { guild_id: 'path' },
      }),
    },
    {
      actionId: 'get_channel',
      name: 'Get channel',
      description: 'Get detailed information about a specific channel.',
      intents: [
        'get discord channel info',
        'look up a channel in discord',
        'channel details',
        'show me info about a discord channel',
        'fetch a specific channel in discord',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the channel.' },
        { name: 'name', type: 'string', description: 'Name of the channel.' },
        { name: 'type', type: 'number', description: 'Channel type: 0=text, 2=voice, 4=category.' },
        { name: 'topic', type: 'string', description: 'Channel topic text.' },
        { name: 'guild_id', type: 'string', description: 'ID of the server this channel belongs to.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/channels/{channel_id}',
        paramMapping: { channel_id: 'path' },
      }),
    },
    {
      actionId: 'create_channel',
      name: 'Create channel',
      description: 'Create a new channel in a Discord server.',
      intents: [
        'make a new discord channel',
        'add a channel to the server',
        'set up a new channel',
        'create a room in discord',
        'open a new channel in discord',
        'spin up a discord channel',
        'start a new text channel in the server',
      ],
      inputFields: [
        {
          name: 'guild_id',
          type: 'string',
          required: true,
          description: 'The ID of the server to create the channel in.',
        },
        {
          name: 'name',
          type: 'string',
          required: true,
          description: 'Name for the new channel.',
        },
        {
          name: 'type',
          type: 'number',
          required: false,
          description: 'Channel type: 0 = text, 2 = voice, 4 = category.',
          default: 0,
        },
        {
          name: 'topic',
          type: 'string',
          required: false,
          description: 'Channel topic (max 1024 characters for text, 256 for forum).',
        },
        {
          name: 'parent_id',
          type: 'string',
          required: false,
          description: 'Parent category ID to nest the channel under.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the newly created channel.' },
        { name: 'name', type: 'string', description: 'Name of the created channel.' },
        { name: 'type', type: 'number', description: 'Channel type: 0=text, 2=voice, 4=category.' },
        { name: 'guild_id', type: 'string', description: 'ID of the server the channel was created in.' },
      ],
      execute: rest({
        method: 'POST',
        path: '/guilds/{guild_id}/channels',
        paramMapping: { guild_id: 'path', name: 'body', type: 'body', topic: 'body', parent_id: 'body' },
      }),
    },
    {
      actionId: 'edit_channel',
      name: 'Edit channel',
      description: "Modify a channel's settings (name, topic, NSFW, slowmode).",
      intents: [
        'rename a discord channel',
        'change channel settings',
        'update the channel topic',
        'adjust slowmode in a discord channel',
        'modify a channel in the server',
        'tweak the discord channel configuration',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel to edit.',
        },
        {
          name: 'name',
          type: 'string',
          required: false,
          description: 'New channel name.',
        },
        {
          name: 'topic',
          type: 'string',
          required: false,
          description: 'New channel topic.',
        },
        {
          name: 'nsfw',
          type: 'boolean',
          required: false,
          description: 'Whether the channel is NSFW.',
        },
        {
          name: 'rate_limit_per_user',
          type: 'number',
          required: false,
          description: 'Slowmode delay in seconds (0-21600). 0 disables slowmode.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the updated channel.' },
        { name: 'name', type: 'string', description: 'Updated channel name.' },
        { name: 'topic', type: 'string', description: 'Updated channel topic.' },
        { name: 'rate_limit_per_user', type: 'number', description: 'Updated slowmode delay in seconds.' },
      ],
      execute: rest({
        method: 'PATCH',
        path: '/channels/{channel_id}',
        paramMapping: { channel_id: 'path', name: 'body', topic: 'body', nsfw: 'body', rate_limit_per_user: 'body' },
      }),
    },
    {
      actionId: 'delete_channel',
      name: 'Delete channel',
      description: 'Permanently delete a channel from a Discord server.',
      intents: [
        'remove a discord channel',
        'delete a room from the server',
        'get rid of a discord channel',
        'wipe a channel from the server',
        'tear down a discord channel',
      ],
      inputFields: [
        {
          name: 'channel_id',
          type: 'string',
          required: true,
          description: 'The ID of the channel to delete.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the deleted channel.' },
        { name: 'name', type: 'string', description: 'Name of the deleted channel.' },
        { name: 'guild_id', type: 'string', description: 'ID of the server the channel was in.' },
      ],
      execute: rest({
        method: 'DELETE',
        path: '/channels/{channel_id}',
        paramMapping: { channel_id: 'path' },
      }),
    },
    // ── Guilds / Servers ─────────────────────────────────────
    {
      actionId: 'list_guilds',
      name: 'List servers',
      description: 'List all Discord servers this integration is connected to.',
      intents: [
        'what discord servers is the bot in',
        'show connected discord servers',
        'list discord guilds',
        'which discord servers are available',
        'see all the servers weldable is in',
        'show me the discord servers I can use',
      ],
      inputFields: [
        {
          name: 'limit',
          type: 'number',
          required: false,
          description: 'Maximum number of servers to return (1-200).',
          default: 100,
        },
      ],
      outputFields: [
        { name: 'guilds', type: 'array', description: 'Array of partial guild objects, each with id, name, and icon.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/users/@me/guilds',
        paramMapping: { limit: 'query' },
      }),
    },
    {
      actionId: 'get_guild',
      name: 'Get guild info',
      description: 'Get detailed information about a Discord server (guild).',
      intents: [
        'get discord server info',
        'look up server details',
        'server information',
        'show me details about a discord server',
        'what do you know about this discord guild',
        'fetch info on a discord server',
      ],
      inputFields: [
        {
          name: 'guild_id',
          type: 'string',
          required: true,
          description: 'The ID of the server.',
        },
        {
          name: 'with_counts',
          type: 'boolean',
          required: false,
          description: 'Whether to include approximate member and presence counts.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Snowflake ID of the server.' },
        { name: 'name', type: 'string', description: 'Name of the server.' },
        { name: 'description', type: 'string', description: 'Server description.' },
        { name: 'approximate_member_count', type: 'number', description: 'Approximate total member count (included when with_counts is true).' },
        { name: 'approximate_presence_count', type: 'number', description: 'Approximate count of online members (included when with_counts is true).' },
      ],
      execute: rest({
        method: 'GET',
        path: '/guilds/{guild_id}',
        paramMapping: { guild_id: 'path', with_counts: 'query' },
      }),
    },
  ],
})
